tools:
    external_code_coverage: true

build:
    services:
        mongo: 4
        postgres: 10
    dependencies:
        before:
            - pecl install mongodb
    environment:
        variables:
            DATABASE_URL: pgsql://scrutinizer:scrutinizer@localhost:5432/scrutinizer
            MONGODB_URL: mongodb://localhost:27017
            MONGODB_DB: botilka
            EVENT_STORE_COLLECTION: event_store
            SNAPSHOT_STORE_COLLECTION: snapshot_store
