tools:
    external_code_coverage: true

build:
    services:
        mongo: 4
        postgres: 10
    dependencies:
        before:
            - pecl install mongodb
    environment:
        variables:
            DATABASE_URL: pgsql://scrutinizer:scrutinizer@localhost:5432/scrutinizer
            POSTGRES_TABLE: event_store
            MONGODB_URL: mongodb://localhost:27017
            MONGODB_DB: botilka
            MONGODB_COLLECTION: event_store
