tools:
    external_code_coverage: true

build:
    services:
        mongo: 4
        postgres: 10
    dependencies:
        before:
            - pecl install mongodb
    environment:
        variables:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
            POSTGRES_DB: database
            POSTGRES_TABLE: event_store
            DATABASE_URL: pgsql://postgres@localhost:5432/database
            MONGODB_HOST: localhost
            MONGODB_PORT: 27017
            MONGODB_DB: botilka_test
            MONGODB_COLLECTION: event_store_test
