services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Botilka\Infrastructure\InMemory\EventStoreInMemory: ~
    Botilka\EventStore\EventStore: '@Botilka\Infrastructure\InMemory\EventStoreInMemory'

    Botilka\Event\EventReplayer:
        class: Botilka\Event\DefaultEventReplayer

    Botilka\Infrastructure\InMemory\EventStoreManagerInMemory: ~
    Botilka\EventStore\EventStoreManager: '@Botilka\Infrastructure\InMemory\EventStoreManagerInMemory'

    Botilka\Ui\Console\EventReplayCommand: ~
    Botilka\Ui\Console\ProjectorReplayCommand: ~

    Botilka\Ui\Console\EventStoreInitializeCommand:
        arguments:
            $initializers: !tagged botilka.event_store.initializer

    Botilka\Projector\Projectionist:
        class: Botilka\Projector\DefaultProjectionist
        arguments:
            $projectors: !tagged botilka.projector
