services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Botilka\Infrastructure\InMemory\EventStoreInMemory: ~
    Botilka\EventStore\EventStore: '@Botilka\Infrastructure\InMemory\EventStoreInMemory'

    Botilka\Event\DefaultEventReplayer: ~
    Botilka\Event\EventReplayer: '@Botilka\Event\DefaultEventReplayer'

    Botilka\Ui\Console\ReplayCommand: ~

    Botilka\Bridge\ApiPlatform\EventListener\CommandResourceClassEventListener:
        arguments:
            $descriptionContainer: '@Botilka\Bridge\ApiPlatform\Resource\Command.description_container'

    Botilka\Bridge\ApiPlatform\EventListener\QueryResourceClassEventListener:
        arguments:
            $descriptionContainer: '@Botilka\Bridge\ApiPlatform\Resource\Query.description_container'

    Botilka\Bridge\ApiPlatform\Metadata\Resource\Factory\BotilkaCommandResourceMetadataFactory:
        decorates: api_platform.metadata.resource.metadata_factory
        arguments:
            $descriptionContainer: '@Botilka\Bridge\ApiPlatform\Resource\Command.description_container'

    Botilka\Bridge\ApiPlatform\Metadata\Resource\Factory\BotilkaQueryResourceMetadataFactory:
        decorates: api_platform.metadata.resource.metadata_factory
        arguments:
            $descriptionContainer: '@Botilka\Bridge\ApiPlatform\Resource\Query.description_container'

    Botilka\Bridge\ApiPlatform\Swagger\SwaggerResourcePayloadNormalizerInterface:
        class: Botilka\Bridge\ApiPlatform\Swagger\SwaggerResourcePayloadNormalizer
