services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Botilka\Infrastructure\InMemory\EventStoreInMemory: ~
    Botilka\EventStore\EventStore: '@Botilka\Infrastructure\InMemory\EventStoreInMemory'

    Botilka\Event\EventReplayer:
        class: Botilka\Event\DefaultEventReplayer

    Botilka\Ui\Console\ReplayCommand: ~

    Botilka\Ui\Console\EventStoreInitializeCommand:
        arguments:
            $initializers: !tagged botilka.event_store.initializable
