services:
    _defaults:
        autowire: true
        public: false

    Botilka\Infrastructure\InMemory\EventStoreInMemory: ~
    Botilka\EventStore\EventStore: '@Botilka\Infrastructure\InMemory\EventStoreInMemory'

    Botilka\Event\EventReplayer: ~
    Botilka\Event\EventReplayerInterface: '@Botilka\Event\EventReplayer'

    Botilka\Ui\Console\ReplayCommand:
        tags: [ 'console.command' ]
