services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Botilka\Infrastructure\InMemory\EventStoreInMemory: ~
    Botilka\EventStore\EventStore: '@Botilka\Infrastructure\InMemory\EventStoreInMemory'

    Botilka\Event\DefaultEventReplayer: ~
    Botilka\Event\EventReplayer: '@Botilka\Event\DefaultEventReplayer'

    Botilka\Ui\Console\ReplayCommand: ~

    Botilka\Bridge\ApiPlatform\EventListener\CommandResourceClassEventListener:
        arguments:
            $descriptionContainer: '@Botilka\Bridge\ApiPlatform\Resource\Command.description_container'

    Botilka\Bridge\ApiPlatform\EventListener\QueryResourceClassEventListener:
        arguments:
            $descriptionContainer: '@Botilka\Bridge\ApiPlatform\Resource\Query.description_container'

    Botilka\Bridge\ApiPlatform\Hydrator\CommandHydratorInterface:
        class: Botilka\Bridge\ApiPlatform\Hydrator\CommandHydrator

    Botilka\Bridge\ApiPlatform\Hydrator\QueryHydratorInterface:
        class: Botilka\Bridge\ApiPlatform\Hydrator\QueryHydrator

    Botilka\Bridge\ApiPlatform\Metadata\Resource\Factory\BotilkaCommandResourceMetadataFactory:
        decorates: api_platform.metadata.resource.metadata_factory
        arguments:
            $descriptionContainer: '@Botilka\Bridge\ApiPlatform\Resource\Command.description_container'
            $payloadNormalizer: '@Botilka\Bridge\ApiPlatform\Swagger\SwaggerCommandBodyNormalizer'


    Botilka\Bridge\ApiPlatform\Metadata\Resource\Factory\BotilkaQueryResourceMetadataFactory:
        decorates: api_platform.metadata.resource.metadata_factory
        arguments:
            $descriptionContainer: '@Botilka\Bridge\ApiPlatform\Resource\Query.description_container'
            $parameterNormalizer: '@Botilka\Bridge\ApiPlatform\Swagger\SwaggerQueryParameterNormalizer'
            $formats: '%api_platform.formats%'

    Botilka\Bridge\ApiPlatform\Swagger\SwaggerQueryParameterNormalizer: ~
    Botilka\Bridge\ApiPlatform\Swagger\SwaggerCommandBodyNormalizer: ~
