services:
    _defaults:
        autowire: true
        public: false

    # activate Doctrine as EventStore
    Botilka\Infrastructure\Doctrine\EventStoreDoctrine: ~
    Botilka\EventStore\EventStore: '@Botilka\Infrastructure\Doctrine\EventStoreDoctrine'
