services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $client: '@MongoDB\Client'
            $database: '%botilka.mongodb.db%'

    MongoDB\Client:
       arguments: ['%botilka.mongodb.url%']

    # MongoDB collections
    MongoDB\Collection.event_store:
        class: MongoDB\Client
        factory: ['@MongoDB\Client', selectCollection]
        arguments: ['%botilka.mongodb.db%', '%botilka.event_store.collection%']

    MongoDB\Collection.snapshot_store:
        class: MongoDB\Client
        factory: ['@MongoDB\Client', selectCollection]
        arguments: ['%botilka.mongodb.db%', '%botilka.snapshot_store.collection%']

    # Event store
    Botilka\Infrastructure\MongoDB\EventStoreMongoDB:
        arguments:
           $collection: '@MongoDB\Collection.event_store'
    Botilka\EventStore\EventStore: '@Botilka\Infrastructure\MongoDB\EventStoreMongoDB'

    # Snapshot store
    Botilka\Infrastructure\MongoDB\SnapshotStoreMongoDB:
        arguments:
            $collection: '@MongoDB\Collection.snapshot_store'
    Botilka\Snapshot\SnapshotStore: '@Botilka\Infrastructure\MongoDB\SnapshotStoreMongoDB'

    # Event store manager
    Botilka\Infrastructure\MongoDB\EventStoreManagerMongoDB:
        arguments:
            $collection: '@MongoDB\Collection.event_store'
    Botilka\EventStore\EventStoreManager: '@Botilka\Infrastructure\MongoDB\EventStoreManagerMongoDB'

    # Initializers
    Botilka\Infrastructure\MongoDB\Initializer\EventStoreMongoDBInitializer:
        arguments:
            $collectionName: '%botilka.event_store.collection%'

    Botilka\Infrastructure\MongoDB\Initializer\SnapshotStoreMongoDBInitializer:
        arguments:
            $collectionName: '%botilka.snapshot_store.collection%'
