services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $client: '@MongoDB\Client'
            $database: '%env(MONGODB_DB)%'


    MongoDB\Client:
       arguments: ['%env(MONGODB_URL)%']

    MongoDB\Collection:
        factory: ['@MongoDB\Client', selectCollection]
        arguments: ['%env(MONGODB_DB)%', '%env(MONGODB_COLLECTION)%']

    Botilka\Infrastructure\MongoDB\EventStoreMongoDB:
        arguments:
           $collection: '@MongoDB\Collection'

    Botilka\EventStore\EventStore: '@Botilka\Infrastructure\MongoDB\EventStoreMongoDB'

    Botilka\Infrastructure\MongoDB\EventStoreManagerMongoDB: ~
    Botilka\EventStore\EventStoreManager: '@Botilka\Infrastructure\MongoDB\EventStoreManagerMongoDB'

    Botilka\Infrastructure\MongoDB\Initializer\EventStoreMongoDBInitializer:
        arguments:
            $collection: '%env(MONGODB_COLLECTION)%'

    Botilka\Infrastructure\MongoDB\Initializer\SnapshotStoreMongoDBInitializer:
        arguments:
            arguments:
                $collection: '%env(SNAPSHOT_STORE_COLLECTION)%'
