services:
    _defaults:
        autowire: true
        public: false
        bind:
            $eventBus: '@Botilka\Bus\Bus.events'

    Botilka\Infrastructure\Symfony\Messenger\Middleware\EventDispatcherBusMiddleware: ~

    Botilka\Event\DefaultEventDispatcher: ~
    Botilka\Event\EventDispatcher: '@Botilka\Event\DefaultEventDispatcher'

    Botilka\Bus\Bus.events:
        class: Botilka\Infrastructure\Symfony\Messenger\SymfonyMessageBus
        arguments:
            $bus: '@messenger.bus.events'
