services:
    _defaults:
        autowire: true
        public: false
        bind:
            $eventBus: '@messenger.bus.events'

    Botilka\Infrastructure\Symfony\Messenger\Middleware\EventDispatcherBusMiddleware: ~

    Botilka\Event\DefaultEventDispatcher: ~
    Botilka\Event\EventDispatcher: '@Botilka\Event\DefaultEventDispatcher'
