services:
    _defaults:
        autowire: true
        public: false

    Botilka\Event\EventBus: '@Botilka\Infrastructure\Symfony\Messenger\MessengerEventBus'
    Botilka\Application\Command\CommandBus: '@Botilka\Infrastructure\Symfony\Messenger\MessengerCommandBus'
    Botilka\Application\Query\QueryBus: '@Botilka\Infrastructure\Symfony\Messenger\MessengerQueryBus'

    Botilka\Infrastructure\Symfony\Messenger\Middleware\EventDispatcherMiddleware: ~

    Botilka\Infrastructure\Symfony\Messenger\MessengerCommandBus:
        arguments:
            $messageBus: '@messenger.bus.commands'

    Botilka\Infrastructure\Symfony\Messenger\MessengerQueryBus:
        arguments:
            $messageBus: '@messenger.bus.queries'

    Botilka\Infrastructure\Symfony\Messenger\MessengerEventBus:
        arguments:
            $messageBus: '@messenger.bus.events'
