services:
    _defaults:
        autowire: true
        public: false
        bind:
            $eventBus: '@Botilka\Infrastructure\Symfony\Messenger\SymfonyEventBus'

    Botilka\Infrastructure\Symfony\Messenger\Middleware\EventDispatcherBusMiddleware: ~

    Botilka\Event\DefaultEventDispatcher: ~
    Botilka\Event\EventDispatcher: '@Botilka\Event\DefaultEventDispatcher'

    Botilka\Infrastructure\Symfony\Messenger\SymfonyEventBus:
        arguments:
            $bus: '@messenger.bus.events'
