services:
    _defaults:
        autowire: true
        public: false
        bind:
            $eventBus: '@messenger.bus.events'

    Botilka\Infrastructure\Symfony\Messenger\Middleware\EventDispatcherBusMiddleware: ~

    Botilka\Event\EventDispatcher: ~
    Botilka\Event\EventDispatcherInterface: '@Botilka\Event\EventDispatcher'
